plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/frankstyles/Library/CloudStorage/GoogleDrive-frankastyles@gmail.com/My Drive/Sole Trader Business/01 - Website/frankstyles-site/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]